FROM python:3.7
MAINTAINER info@ooclab.com

ENV PYTHONIOENCODING=utf-8
ENV PYTHONPATH=/work
ENV PATH /usr/local/bin:$PATH

COPY requirements.dev.txt /requirements.txt
RUN pip3 install -r /requirements.txt && rm /requirements.txt

WORKDIR /work
VOLUME /data
EXPOSE 3000
