swagger: '2.0'
info:
  version: '1.0'
  title: 'foo'
  description: |
    `Foo Service` -- 提供...服务

    ## 约定

    - 命名中英文无论单复数尽量统一用单数形式
    - 表示时间的字符串如无特别说明，统一指 RFC3339 UTC 格式，示例： `2017-05-30T01:45:39.871980Z`

  contact:
    name: OOCLAB
    url: 'https://ooclab.com'
    email: info@ooclab.com

host: localhost:3000
schemes:
- http

tags:
- name: role
  description: 角色

paths:

  "/":
    get:
      tags:
      - default
      summary: 获取 YAML 格式的 SwaggerUI 文档（即本文档）
      produces:
      - application/yaml
      responses:
        "200":
          description: 返回 YAML 文档

  "/_health":
    get:
      tags:
      - default
      summary: 查看健康状态
      responses:
        "200":
          description: 返回 "ok" 表示服务运行健康

  "/role":

    parameters:
    - $ref: '#/parameters/Authorization'

    get:
      tags:
      - role
      summary: 获取所有角色列表
      parameters:
      - $ref: '#/parameters/PageSize'
      - $ref: '#/parameters/Page'
      - $ref: '#/parameters/ASC'
      - name: sort_by
        in: query
        type: string
        description: 排序依据的属性
        enum:
        - created
        - name
      responses:
        "200":
          description: OK
          schema:
            type: object
            required:
            - data
            - filter
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/RoleSimple'
              filter:
                $ref: '#/definitions/PageFilter'
        default:
          description: 返回错误信息
          schema:
            $ref: '#/definitions/DefaultErrorResponse'

    post:
      tags:
      - role
      summary: 创建新角色
      parameters:
      - name: body
        in: body
        schema:
          type: object
          required:
          - name
          properties:
            name:
              type: string
              description: 名称（必须全局唯一）
              minLength: 2
              maxLength: 128
            summary:
              type: string
              description: 描述
              maxLength: 256
            description:
              type: string
              description: 详细描述
      responses:
        "200":
          description: OK
        default:
          description: |
            返回错误信息
            error 值及含义：
            - `name-exist` : 名字已经存在
          schema:
            $ref: '#/definitions/DefaultErrorResponse'

  "/role/{id}":

    parameters:
    - $ref: '#/parameters/Authorization'
    - $ref: '#/parameters/PathRoleID'

    get:
      tags:
      - role
      summary: 获取指定角色详情
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
                default: "success"
              data:
                $ref: '#/definitions/Role'
        default:
          description: |
            返回错误信息
            error 值及含义：
            - `not-found` : 名称不存在
          schema:
            $ref: '#/definitions/DefaultErrorResponse'

    post:
      tags:
      - role
      summary: 更新指定角色信息
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            summary:
              type: string
              description: 描述
              maxLength: 256
            description:
              type: string
              description: 详细描述
              maxLength: 8192
      responses:
        "200":
          description: OK
        default:
          description: |
            返回错误信息
            error 值及含义：
            - `not-found` : 名称不存在
          schema:
            $ref: '#/definitions/DefaultErrorResponse'

    delete:
      tags:
      - role
      summary: 删除指定角色
      responses:
        "200":
          description: OK
        default:
          description: |
            返回错误信息
            error 值及含义：
            - `not-found` : 名称不存在
          schema:
            $ref: '#/definitions/DefaultErrorResponse'


definitions:

  DefaultErrorResponse:
    type: object
    required:
    - status
    properties:
      status:
        type: string
        description: 错误字符串
      message:
        type: string
        description: 错误描述信息
      errors:
        type: string
        description: 有多个错误值时（通常发生在验证表单失败时）
      data:
        type: object
        properties:
          status_code:
            type: integer
            format: int
            description: 错误码
          exc_info:
            type: string
            description: 详细错误信息

  RoleSimple:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: string
        format: uuid
        description: 角色ID
      name:
        type: string
        description: 角色名称（全局唯一）
      summary:
        type: string
        description: 角色描述

  Role:
    type: object
    description: 角色
    required:
    - id
    - name
    - summary
    - created
    - updated
    properties:
      id:
        type: string
        format: uuid
        description: 角色ID
      name:
        type: string
        description: 名字
      summary:
        type: string
        description: 描述
      description:
        type: string
        description: 详细描述
      created:
        type: string
        format: date-time
        description: 创建时间
      updated:
        type: string
        format: date-time
        description: 更新时间

  PageFilter:
    type: object
    description: 数据过滤选项
    required:
    - page_size
    - page
    - total
    - sort_by
    - asc
    properties:
      page_size:
        type: integer
        format: int
        minimum: 10
        maximum: 100
        default: 10
        description: 分页大小
      page:
        type: integer
        format: int
        minimum: 1
        default: 1
        description: 当前返回页
      total:
        type: integer
        format: int
        description: 总数
      sort_by:
        type: string
        description: 排序属性
      asc:
        type: boolean
        default: false
        description: 是否为正序排列？


parameters:

  Authorization:
    name: Authorization
    in: header
    type: string
    description: 提供 JWT Token, 格式 `"Bearer {TOKEN}"`
    required: true

  PathRoleID:
    name: id
    in: path
    required: true
    type: string
    format: uuid
    description: 角色ID

  ASC:
    name: asc
    in: query
    type: string
    default: "false"
    enum:
    - "true"
    - "false"
    - "1"
    - "0"
    description: 表示是否使用升序排列，默认为降序

  Page:
    name: current_page
    in: query
    type: integer
    format: int
    default: 1
    minimum: 1
    description: 需要查看的页数

  PageSize:
    name: page_size
    in: query
    type: integer
    format: int
    default: 10
    minimum: 10
    maximum: 100
    description: 页数大小
